# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\EYAZIS\ILang1\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_search = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_search.setGeometry(QtCore.QRect(100, 30, 721, 31))
        self.textEdit_search.setObjectName("textEdit_search")
        self.label_search = QtWidgets.QLabel(self.centralwidget)
        self.label_search.setGeometry(QtCore.QRect(20, 30, 71, 17))
        self.label_search.setObjectName("label_search")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(380, 80, 100, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\EYAZIS\\ILang1\\search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menuhelp.addAction(self.actionhelp)
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search"))
        self.textEdit_search.setStatusTip(_translate("MainWindow", "Search field"))
        self.label_search.setText(_translate("MainWindow", "Search string"))
        self.btn_search.setStatusTip(_translate("MainWindow", "Search"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.menuhelp.setTitle(_translate("MainWindow", "menu"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionhelp.setStatusTip(_translate("MainWindow", "Show help menu"))
        self.actionhelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
